# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - release*
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Mount caches
        uses: actions/cache@v2
        with:
          path: |
            "/home/runner/.cache/bazel"
            "/home/runner/.m2/repository"
          key: caches-${{ runner.os }}
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.6.1
      - name: Test All
        run: bazel test //...
      - name: Test Kramer
        run: (cd kramer && bazel test //...)
      - name: Build the Test Workspace
        run: (cd test/test_workspace && bazel build //...)
      - name: Test the Test Workspace
        run: (cd test/test_workspace && bazel test //...)

  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.m2/repository"
        key: caches-${{ runner.os }}
    - name: Setup bazelisk for Bazel builds
      uses: holvonix-open/setup-bazelisk@v0.6.1
    - name: Test All
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...
    - name: Test Kramer
      run: |
        (cd kramer && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
    - name: Build the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" build //...)
    - name: Test the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" test //...)

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.m2/repository"
        key: caches-${{ runner.os }}
    - name: Setup bazelisk for Bazel builds
      uses: holvonix-open/setup-bazelisk@v0.6.1
    - name: Test All
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...
    - name: Test Kramer
      run: |
        (cd kramer && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
    - name: Build the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" build //...)
    - name: Test the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
